#!/usr/bin/php
# first npm install -g jshint
# jshint

<?php

$error = false;
// $path = "~/miiitv_plus/";
$path = "";

exec("git diff --cached --name-only --diff-filter=ACM | grep '\.js'", $output_js, $return_var);

if (!empty($output_js))
{
    foreach ($output_js as $file) {
        $file_path = $path . $file;
        if (!empty(shell_exec("jshint " . $file_path . "")))
        {
            echo $file_path;
            echo "\n";
            echo "--------------------";
            echo "\n";
            echo shell_exec("jshint " . $file_path . "");
            echo "\n";
            echo "====================";
            $error = true;
        }
    }
}



# http://tedshd.logdown.com/posts/246406-php-install-phpcsphp-codesniffer
# phpcs

exec("git diff --cached --name-only --diff-filter=ACM | grep '\.php'", $output_php, $return_var);

if (!empty($output_php))
{
    foreach ($output_php as $file) {
        $file_path = $path . $file;
        if (!empty(shell_exec("phpcs " . $file_path . "")))
        {
            echo $file_path;
            echo "\n";
            echo "--------------------";
            echo "\n";
            echo shell_exec("phpcs " . $file_path . "");
            echo "\n";
            echo "====================";
            $error = true;
        }
    }
}

if ($error)
{
    exit(1);
}
else
{
    exit(0);
}

?>
